title: Atilla Tanrikulu
baseurl: "/" # the subpath of your site, e.g. /blog
domain-name: atilla.tanrikulu.biz
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: atillatanrikulu
github_username:  atillatan
keywords: >- # this means to ignore newlines until "description:"
  java, c#, csharp, code, coding, sql, redis, cache, script, javascript
description: >- # this means to ignore newlines until "author:"
  atilla.tanrikulu.biz | Bir çok kategoride güzel ve özgün makaleler okuyabileceğiniz güncel bir blog
author: Atilla Tanrikulu
environment: production
permalink: pretty
markdown: kramdown
highlighter: rouge
img: /assets/img
disqus:
  shortname: atilla-tanrikulu-biz
#google_analytics: UA-2498474-2

# Build settings

plugins:
  - jekyll-feed

exclude:
  - Readme.md
  - node_modules
  - lib

collections:
  downloads:
    output: true
    permalink: /downloads/:path/
  articles:
    output: true
    permalink: /:path/
