title: Atilla Tanrikulu
description: >- # this means to ignore newlines until "baseurl:"
  atilla.tanrikulu.biz | Bir çok kategoride güzel ve özgün makaleler okuyabileceğiniz güncel bir blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: atillatanrikulu
github_username:  atillatan
environment: production
permalink: pretty
highlighter: rouge
#google_analytics: UA-2498474-2

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Readme.md
  - node_modules
  - lib

collections:
  downloads:
    output: true
    permalink: /downloads/:path/
